/* Generated by npm run pattern:calibrate. */
import type { PatternFamilyId } from "./pattern";
export type PatternCalibration = Readonly<{ status: "CALIBRATED" | "WEAK_SEPARATION" | "UNAVAILABLE"; reason?: string; positiveCount: number; hardNegativeCount: number; controlCount: number; presenceThreshold?: number; targetTrigger?: number; points?: readonly (readonly [number, number])[] }>;
export const PATTERN_CALIBRATION_MODEL_VERSION = "mate-geometry-v2-calibration-v3";
export const PATTERN_CALIBRATION_DATASET_VERSION = "puzzle-mvp-2026-09-controlled";
export const PATTERN_CALIBRATION_SHA256 = "a772c7bbdb5e8c5981033c1893d8dc3ddbba9185302476916497777864172f64";
export const PATTERN_CALIBRATION: Readonly<Partial<Record<PatternFamilyId, PatternCalibration>>> = {
  "ANASTASIA": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 8,
    "presenceThreshold": 0.9,
    "targetTrigger": 0.9,
    "points": [
      [
        0,
        0.52
      ],
      [
        0.06,
        0.52
      ],
      [
        0.07,
        0.5368
      ],
      [
        0.08,
        0.5556
      ],
      [
        0.09,
        0.5765
      ],
      [
        0.11,
        0.6
      ],
      [
        0.1109,
        0.6923
      ],
      [
        0.118,
        0.7333
      ],
      [
        0.13,
        0.7818
      ],
      [
        0.15,
        0.84
      ],
      [
        0.2676,
        0.9111
      ],
      [
        0.2722,
        0.9111
      ],
      [
        0.28,
        0.9111
      ],
      [
        0.3422,
        0.9111
      ],
      [
        0.3422,
        0.9111
      ],
      [
        0.8,
        0.9111
      ],
      [
        0.84,
        0.9111
      ],
      [
        0.9,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "ARABIAN": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.465,
    "targetTrigger": 0.465,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.0833,
        0.7333
      ],
      [
        0.38,
        0.84
      ],
      [
        0.445,
        0.9111
      ],
      [
        0.465,
        1
      ],
      [
        0.7767,
        1
      ],
      [
        0.78,
        1
      ],
      [
        0.8667,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "BACK_RANK": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.2639,
    "targetTrigger": 0.3422,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.11,
        0.7333
      ],
      [
        0.12,
        0.84
      ],
      [
        0.1894,
        0.9111
      ],
      [
        0.2639,
        1
      ],
      [
        0.3422,
        1
      ],
      [
        0.3578,
        1
      ],
      [
        0.465,
        1
      ],
      [
        0.485,
        1
      ],
      [
        0.495,
        1
      ],
      [
        0.525,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "BALESTRA": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.465,
    "targetTrigger": 0.465,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.11,
        0.7333
      ],
      [
        0.1299,
        0.7818
      ],
      [
        0.13,
        0.84
      ],
      [
        0.465,
        1
      ],
      [
        0.9,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "BLIND_SWINE": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.525,
    "targetTrigger": 0.525,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.0833,
        0.7333
      ],
      [
        0.1631,
        0.7818
      ],
      [
        0.3879,
        0.84
      ],
      [
        0.405,
        0.9111
      ],
      [
        0.525,
        1
      ],
      [
        0.5476,
        1
      ],
      [
        0.5878,
        1
      ],
      [
        0.7562,
        1
      ],
      [
        0.7848,
        1
      ],
      [
        0.8133,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "BODEN": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.405,
    "targetTrigger": 0.81,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.075,
        0.7333
      ],
      [
        0.11,
        0.7818
      ],
      [
        0.135,
        0.9111
      ],
      [
        0.405,
        1
      ],
      [
        0.81,
        1
      ],
      [
        0.82,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "CORNER": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.39,
    "targetTrigger": 0.39,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.0567,
        0.7333
      ],
      [
        0.1639,
        0.7818
      ],
      [
        0.1972,
        0.7818
      ],
      [
        0.2244,
        0.8222
      ],
      [
        0.2717,
        0.8222
      ],
      [
        0.325,
        0.8857
      ],
      [
        0.39,
        1
      ],
      [
        0.525,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "DOUBLE_BISHOP": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.1619,
    "targetTrigger": 0.1763,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.11,
        0.7333
      ],
      [
        0.15,
        0.7818
      ],
      [
        0.1619,
        1
      ],
      [
        0.1719,
        1
      ],
      [
        0.1763,
        1
      ],
      [
        0.183,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "DOVETAIL": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.2022,
    "targetTrigger": 0.2567,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.0867,
        0.7333
      ],
      [
        0.0944,
        0.7818
      ],
      [
        0.12,
        0.84
      ],
      [
        0.1758,
        0.9111
      ],
      [
        0.2022,
        1
      ],
      [
        0.2333,
        1
      ],
      [
        0.252,
        1
      ],
      [
        0.2567,
        1
      ],
      [
        0.335,
        1
      ],
      [
        0.7333,
        1
      ],
      [
        0.7383,
        1
      ],
      [
        0.8,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "EPAULETTE": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.495,
    "targetTrigger": 0.495,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.135,
        0.7333
      ],
      [
        0.159,
        0.7818
      ],
      [
        0.375,
        0.84
      ],
      [
        0.3889,
        0.8857
      ],
      [
        0.405,
        0.8857
      ],
      [
        0.465,
        0.8857
      ],
      [
        0.495,
        1
      ],
      [
        0.75,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "HOOK": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.325,
    "targetTrigger": 0.325,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.09,
        0.7333
      ],
      [
        0.1067,
        0.7818
      ],
      [
        0.1139,
        0.84
      ],
      [
        0.1182,
        0.9111
      ],
      [
        0.1631,
        0.9111
      ],
      [
        0.325,
        1
      ],
      [
        0.56,
        1
      ],
      [
        0.75,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "KILL_BOX": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.5378,
    "targetTrigger": 0.5378,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.0911,
        0.7333
      ],
      [
        0.205,
        0.7818
      ],
      [
        0.315,
        0.84
      ],
      [
        0.365,
        0.9
      ],
      [
        0.5378,
        1
      ],
      [
        0.65,
        1
      ],
      [
        0.8,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "PILLSBURY": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.161,
    "targetTrigger": 0.161,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.11,
        0.7333
      ],
      [
        0.1199,
        0.7818
      ],
      [
        0.121,
        0.7818
      ],
      [
        0.1224,
        0.7818
      ],
      [
        0.1242,
        0.8667
      ],
      [
        0.1266,
        0.8667
      ],
      [
        0.161,
        1
      ],
      [
        0.405,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "MORPHYS": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.411,
    "targetTrigger": 0.411,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.1167,
        0.7333
      ],
      [
        0.1486,
        0.7818
      ],
      [
        0.1804,
        0.7818
      ],
      [
        0.193,
        0.7818
      ],
      [
        0.245,
        0.7818
      ],
      [
        0.249,
        0.8667
      ],
      [
        0.365,
        0.8667
      ],
      [
        0.405,
        0.8667
      ],
      [
        0.411,
        1
      ],
      [
        0.417,
        1
      ],
      [
        0.465,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "OPERA": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.8067,
    "targetTrigger": 0.8067,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.098,
        0.7333
      ],
      [
        0.111,
        0.7818
      ],
      [
        0.1238,
        0.84
      ],
      [
        0.135,
        0.84
      ],
      [
        0.1398,
        0.84
      ],
      [
        0.1539,
        0.84
      ],
      [
        0.167,
        0.8667
      ],
      [
        0.321,
        0.8667
      ],
      [
        0.377,
        0.8667
      ],
      [
        0.8067,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "SMOTHERED": {
    "status": "WEAK_SEPARATION",
    "reason": "no high-precision operating point",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0,
    "targetTrigger": 1,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.9,
        0.7333
      ],
      [
        1,
        0.76
      ]
    ]
  },
  "SWALLOWTAIL": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.525,
    "targetTrigger": 0.525,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.09,
        0.7333
      ],
      [
        0.098,
        0.7818
      ],
      [
        0.1,
        0.84
      ],
      [
        0.1039,
        0.84
      ],
      [
        0.108,
        0.8667
      ],
      [
        0.123,
        0.8667
      ],
      [
        0.161,
        0.8667
      ],
      [
        0.495,
        0.8667
      ],
      [
        0.525,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "TRIANGLE": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.405,
    "targetTrigger": 0.405,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.0729,
        0.7333
      ],
      [
        0.1639,
        0.7818
      ],
      [
        0.255,
        0.84
      ],
      [
        0.315,
        0.9111
      ],
      [
        0.319,
        0.9111
      ],
      [
        0.323,
        0.9111
      ],
      [
        0.365,
        0.9111
      ],
      [
        0.405,
        1
      ],
      [
        0.417,
        1
      ],
      [
        0.42,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "VUKOVIC": {
    "status": "CALIBRATED",
    "positiveCount": 8,
    "hardNegativeCount": 4,
    "controlCount": 0,
    "presenceThreshold": 0.525,
    "targetTrigger": 0.525,
    "points": [
      [
        0,
        0.7333
      ],
      [
        0.1267,
        0.7333
      ],
      [
        0.1367,
        0.7818
      ],
      [
        0.183,
        0.84
      ],
      [
        0.1942,
        0.9111
      ],
      [
        0.485,
        0.9111
      ],
      [
        0.525,
        1
      ],
      [
        0.75,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "DAMIANO": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "GRECO": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "LOLLI": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "LEGAL": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "BLACKBURNE": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "ANDERSSEN": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "MAYET": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "RETI": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "MAX_LANGE": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "SUFFOCATION": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "LAWNMOWER": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "DAVID_GOLIATH": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "TWO_KNIGHTS": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "H_FILE": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  },
  "DIAGONAL_CORRIDOR": {
    "status": "UNAVAILABLE",
    "reason": "no verified calibration fixtures",
    "positiveCount": 0,
    "hardNegativeCount": 0,
    "controlCount": 0
  }
};
