import type { PatternFamilyId } from "./pattern";

/**
 * Production trigger calibration generated by `npm run pattern:calibrate`
 * from the checked-in calibration split. The JSON artifact beside this file
 * records the dataset, method, and per-family sample counts.
 */
const CALIBRATED_TRIGGER_THRESHOLDS: Readonly<Partial<Record<PatternFamilyId, number>>> = {
  ANASTASIA: 0.855,
  ARABIAN: 0.823,
  BACK_RANK: 0.325,
  BALESTRA: 0.442,
  BLIND_SWINE: 0.461,
  BODEN: 0.108,
  CORNER: 0.499,
  DOUBLE_BISHOP: 0.163,
  DOVETAIL: 0.259,
  EPAULETTE: 0.442,
  HOOK: 0.309,
  KILL_BOX: 0.385,
  MORPHYS: 0.442,
  OPERA: 0.358,
  PILLSBURY: 0.385,
  SMOTHERED: 0.950,
  SWALLOWTAIL: 0.470,
  TRIANGLE: 0.396,
  VUKOVIC: 0.499
};

export const patternTargetTriggerFor = (family: PatternFamilyId): number => CALIBRATED_TRIGGER_THRESHOLDS[family] ?? 0.97;

export const patternPresenceThresholdFor = (family: PatternFamilyId): number => patternTargetTriggerFor(family) * 0.75;

export const calibratedAttractorScore = (rawAffinity: number, family: PatternFamilyId): number => Math.max(0, Math.min(1, rawAffinity / Math.max(0.000001, patternTargetTriggerFor(family))));

export const patternTriggerThresholdFor = patternTargetTriggerFor;

export const patternTriggerThresholds = (): Readonly<Partial<Record<PatternFamilyId, number>>> => ({ ...CALIBRATED_TRIGGER_THRESHOLDS });
